permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from

remote_theme: dhilanr/jekyll-theme-crestlex

url: https://tinyml.seas.harvard.edu
baseurl: /EASI-22

title: EASI 2022

alert:
    - success